In [1]:
#Interaction with database

import sqlite3 as sqlite3
import pandas as pd
data = {
    'Name': ['Project A', 'Project B', 'Project C'],
    'Age': ['Alice', 'Bob', 'Charlie'],
    'City': ['Completed', 'In Progress', 'Pending'],
 }
results_df = pd.DataFrame(data)


connection = sqlite3.connect('project_results.db')
results_df.to_sql('project_results', con=connection, if_exists='replace', index=False)
connection.commit()
connection.close()
 
connection = sqlite3.connect('project_results.db')
stored_results_df = pd.read_sql_query('SELECT * FROM project_results', con=connection)
print("Data stored in the database:")
print(stored_results_df)
connection.close()

Data stored in the database:
     Project  Manager       Status Completion_Date
0  Project A    Alice    Completed      2024-01-15
1  Project B      Bob  In Progress      2024-03-20
2  Project C  Charlie      Pending            None


In [ ]:
#Method Overloading

class Calculator:
    # Single method with default values for overloading behavior
    def add(self, a=0, b=0, c=0):
        return a + b + c

# Creating an object of the class
cal = Calculator()
# Calling the add method with two arguments
print(cal.add(10, 20))  # Output: 30

# Calling the add method with three arguments
print(cal.add(10, 20, 30))  # Output: 60

# Calling the add method with no arguments
print(cal.add())  # Output: 0


In [1]:
#Slicing

import numpy as np

# Create a 1D NumPy array
a = np.array([10, 20, 30, 40, 50, 60, 70])

# Slicing the 1D array (from index 1 to 4)
print("1D Array Slice (1:5):", a[1:5])  # Output: [20 30 40 50]

# Slicing with a step of 2
print("1D Array Slice with Step (0::2):", a[::2])  # Output: [10 30 50 70]

# Slicing in reverse
print("1D Array Reverse Slice (::-1):", a[::-1])  # Output: [70 60 50 40 30 20 10]

# Create a 2D NumPy array (matrix)
b = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Slicing the 2D array (first two rows and columns 1 to 2)
print("\n2D Array Slice (0:2, 1:3):")
print(b[0:2, 1:3])  # Output: [[2 3]
                    #          [5 6]]

# Slicing to get the first column
print("\n2D Array First Column Slice (:, 0):")
print(b[:, 0])  # Output: [1 4 7]

# Slicing to get the last row
print("\n2D Array Last Row Slice (-1, :):")
print(b[-1, :])  # Output: [7 8 9]


1D Array Slice (1:5): [20 30 40 50]
1D Array Slice with Step (0::2): [10 30 50 70]
1D Array Reverse Slice (::-1): [70 60 50 40 30 20 10]

2D Array Slice (0:2, 1:3):
[[2 3]
 [5 6]]

2D Array First Column Slice (:, 0):
[1 4 7]

2D Array Last Row Slice (-1, :):
[7 8 9]


In [2]:
text = '16 Bolton Avenue , Boston'
print(text.split(','))
#['16 Bolton Avenue ', 'Boston']

strings = ['A+','A','A-','B','BB','BBB','C+']
print(';'.join(strings))
#'A+;A;A-;B;BB;BBB;C+'

['16 Bolton Avenue ', ' Boston']
A+;A;A-;B;BB;BBB;C+


In [4]:
import pandas as pd
data = {'color' : ['blue','green','yellow','red','white'],
'object' : ['ball','pen','pencil','paper','mug'],
'price' : [1.2,1.0,0.6,0.9,1.7]}
df = pd.DataFrame(data)
df


color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [9]:
df['new']=[12,13,14,15,16]
df

color  object  price  new
0    blue    ball    1.2   12
1   green     pen    1.0   13
2  yellow  pencil    0.6   14
3     red   paper    0.9   15
4   white     mug    1.7   16

In [12]:
df.isin([1.0,'pen',13])

color  object  price    new
0  False   False  False  False
1  False    True   True   True
2  False   False  False  False
3  False   False  False  False
4  False   False  False  False

In [13]:
del df['new']
df

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [18]:
df[df['price']<1.2]

color  object  price
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9

In [21]:
print(df)
df.idxmax()

    color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7


color     2
object    2
price     4
dtype: int64

In [22]:
df.idxmin()

color     0
object    0
price     2
dtype: int64

In [27]:
a=pd.DataFrame(np.arange(9).reshape((3,3)))
print(a.to_html())

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>0</th>
      <th>1</th>
      <th>2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>1</td>
      <td>2</td>
    </tr>
    <tr>
      <th>1</th>
      <td>3</td>
      <td>4</td>
      <td>5</td>
    </tr>
    <tr>
      <th>2</th>
      <td>6</td>
      <td>7</td>
      <td>8</td>
    </tr>
  </tbody>
</table>


In [28]:
frame = pd.DataFrame(np.random.random((4,4)),
                     index = ['white','black','red','blue'],
                     columns = ['up','down','right','left'])
frame

up      down     right      left
white  0.571301  0.565658  0.734415  0.484221
black  0.056047  0.501367  0.867352  0.035202
red    0.166197  0.834873  0.816337  0.106643
blue   0.411341  0.417810  0.453199  0.704181

In [33]:
s=['<html>']
s.append('<head><title>HTML</title></head>')
s.append('<body>')
s.append(frame.to_html())
s.append('</body></html>')
html= " ".join(s)

In [34]:
html_file=open('myFrame.html','w')
html_file.write(html)
html_file.close()

In [35]:
df = pd.DataFrame({ 'color': ['white','white','red','red','white'],
                       'value': [2,1,3,3,2]})
df

color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [38]:
df[df.duplicated()]

color  value
3    red      3
4  white      2